### ISSUE TITLE
ERROR: Failed to concat aac files: exit status 1

### ISSUE THREAD

**Issue by takenM** [l3msh0/radicaster#18]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/11594083/137953079-c5678026-be58-48fb-b668-bf9927a572e5.png">

他の番組の録音では起きなかったです。長いからでしょうか...?
他の２時間番組はできたので失敗する理由はまだわかってません...

[こちら](https://github.com/yyoshiki41/radigo#known-issues)の対処をするべきという感じでしょうか？
こちらの問題と同じかと思いまして
https://github.com/yyoshiki41/radigo/issues/22#issuecomment-354046317

aws殆ど触ったことないので、的外れな指摘でしたらすみません...

**Comment by mtmtcode** [comment]
@takenM ご報告ありがとうございます！

手元では再現できなかったのですが、スタックトレースを見る限り内部でradigoを実行した際に記載いただいたリンクと同様の問題が発生したものと思われます。
ただし、radigo側で対策として挙げられているファイルディスクリプタの上限変更はLambdaの制約によりradicasterでは実施できません(1024固定) :bow:

根本解決ではないのですが、以下のようなコマンドにより録音を再実行するとうまくいく可能性があるかもしれません。
`aws lambda invoke --function-name radicaster-rec-radiko --payload '{"id":"cowboy"}' /dev/stdout`

私もTBSの爆笑問題カーボーイを毎週録音しているのですが同様の事象に遭遇したことはないので、番組やアプリケーション側の問題というよりはLambdaの実行コンテキスト等に起因するものではないかと推察しています。

**Comment by takenM** [comment]
@mtmtcode
上記のコマンドで録音再実行できました！ありがとうございます！
定義アップロードの録音の際に起きるような気がします。検証してないのでなんとも言えませんが、この番組以外でも何度か起きましたこと報告しておきます

ちなみに自分の環境は aws cli のバージョンが2以上だったので、`--cli-binary-format raw-in-base64-out`オプションもしくは`~/.aws/config`で`cli_binary_format=raw-in-base64-out`の設定が必要なようで少しハマりました。
同様の事象の対処される方のために念の為書いておきます。

リファレンス: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam

**Comment by mtmtcode** [comment]
@takenM ご丁寧にありがとうございます。
現状解決が難しそうなのですが、引き続き対策検討してみますね。

AWS CLIの件もありがとうございます。自分の環境でその設定を入れてるのをすっかり失念しておりました🙇‍♂️他の方の参考になると思います。
